/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConditionDto
 */
export interface ConditionDto {
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    shortName?: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    code?: string;
}
