/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DahmmDto
 */
export interface DahmmDto {
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DahmmDto
     */
    about?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    input?: string;
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    condition?: string;
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    maintainer?: string;
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    iilFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof DahmmDto
     */
    iilTo?: string;
}
