/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActionDto } from './action-dto';
import { ConditionDto } from './condition-dto';
/**
 * 
 * @export
 * @interface IilDto
 */
export interface IilDto {
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    version?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IilDto
     */
    help?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IilDto
     */
    about?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    goal?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IilDto
     */
    input?: { [key: string]: any; };
    /**
     * 
     * @type {ConditionDto}
     * @memberof IilDto
     */
    activateIf?: ConditionDto;
    /**
     * 
     * @type {ActionDto}
     * @memberof IilDto
     */
    act?: ActionDto;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    actor?: string;
    /**
     * 
     * @type {ConditionDto}
     * @memberof IilDto
     */
    finishIf?: ConditionDto;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IilDto
     */
    output?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    maintainer?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    owner?: string;
    /**
     * 
     * @type {ConditionDto}
     * @memberof IilDto
     */
     abortIf?: ConditionDto;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    state?: IilDtoStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof IilDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IilDto
     */
    next?: { [key: string]: any; };
}

/**
    * @export
    * @enum {string}
    */
export enum IilDtoStateEnum {
    NOTACTIVATED = 'NOTACTIVATED',
    ACTIVE = 'ACTIVE',
    PENDING = 'PENDING',
    FINISHED = 'FINISHED',
    ABORTED = 'ABORTED'
}

