/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DahmmDto } from './dahmm-dto';
/**
 * 
 * @export
 * @interface IilDto
 */
export interface IilDto {
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    version?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IilDto
     */
    help?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IilDto
     */
    about?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    goal?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    input?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    activateIf?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    act?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    actor?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    finishIf?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    output?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    maintainer?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    state?: IilDtoStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof IilDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<DahmmDto>}
     * @memberof IilDto
     */
    dahmm?: Array<DahmmDto>;
}

/**
    * @export
    * @enum {string}
    */
export enum IilDtoStateEnum {
    NOTACTIVATED = 'NOTACTIVATED',
    ACTIVE = 'ACTIVE',
    FOCUSED = 'FOCUSED',
    PENDING = 'PENDING',
    FINISHED = 'FINISHED',
    ACHIEVED = 'ACHIEVED'
}

