/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NextFlowDto
 */
export interface NextFlowDto {
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof NextFlowDto
     */
    describe?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    input?: string;
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    condition?: string;
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    creator?: string;
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof NextFlowDto
     */
    to?: string;
}
