/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FlowDto } from './flow-dto';
/**
 * 
 * @export
 * @interface IilDto
 */
export interface IilDto {
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    goal?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    given?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    startWhen?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    act?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    actor?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    endWhen?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    produce?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    ownedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof IilDto
     */
    status?: IilDtoStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof IilDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IilDto
     */
    lastUpdatedAt?: Date;
    /**
     * 
     * @type {Array<FlowDto>}
     * @memberof IilDto
     */
    leadTo?: Array<FlowDto>;
}

/**
    * @export
    * @enum {string}
    */
export enum IilDtoStatusEnum {
    NOTINITIATED = 'NOTINITIATED',
    ACTIVE = 'ACTIVE',
    FOCUSED = 'FOCUSED',
    PENDING = 'PENDING',
    SETTLED = 'SETTLED'
}

